[package]
name = "rest-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log        = "0.4"
env_logger = "0.10"
actix-web  = "4"
clap       = { version = "4", features = [ "derive" ] }
signalling = { path = "../signalling", features = [ "actix" ] }
